/*
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SummaryGear;
import java.io.IOException;

/**
 * DetailedGear
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T15:31:53.751+01:00")
public class DetailedGear {
  @SerializedName("id")
  private String id = null;

  @SerializedName("resource_state")
  private Integer resourceState = null;

  @SerializedName("primary")
  private Boolean primary = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("distance")
  private Float distance = null;

  @SerializedName("brand_name")
  private String brandName = null;

  @SerializedName("model_name")
  private String modelName = null;

  @SerializedName("frame_type")
  private Integer frameType = null;

  @SerializedName("description")
  private String description = null;

  public DetailedGear id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The gear&#39;s unique identifier.
   * @return id
  **/
  @ApiModelProperty(value = "The gear's unique identifier.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DetailedGear resourceState(Integer resourceState) {
    this.resourceState = resourceState;
    return this;
  }

   /**
   * Resource state, indicates level of detail. Possible values: 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
   * @return resourceState
  **/
  @ApiModelProperty(value = "Resource state, indicates level of detail. Possible values: 2 -> \"summary\", 3 -> \"detail\"")
  public Integer getResourceState() {
    return resourceState;
  }

  public void setResourceState(Integer resourceState) {
    this.resourceState = resourceState;
  }

  public DetailedGear primary(Boolean primary) {
    this.primary = primary;
    return this;
  }

   /**
   * Whether this gear&#39;s is the owner&#39;s default one.
   * @return primary
  **/
  @ApiModelProperty(value = "Whether this gear's is the owner's default one.")
  public Boolean isPrimary() {
    return primary;
  }

  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }

  public DetailedGear name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The gear&#39;s name.
   * @return name
  **/
  @ApiModelProperty(value = "The gear's name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DetailedGear distance(Float distance) {
    this.distance = distance;
    return this;
  }

   /**
   * The distance logged with this gear.
   * @return distance
  **/
  @ApiModelProperty(value = "The distance logged with this gear.")
  public Float getDistance() {
    return distance;
  }

  public void setDistance(Float distance) {
    this.distance = distance;
  }

  public DetailedGear brandName(String brandName) {
    this.brandName = brandName;
    return this;
  }

   /**
   * The gear&#39;s brand name.
   * @return brandName
  **/
  @ApiModelProperty(value = "The gear's brand name.")
  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }

  public DetailedGear modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * The gear&#39;s model name.
   * @return modelName
  **/
  @ApiModelProperty(value = "The gear's model name.")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public DetailedGear frameType(Integer frameType) {
    this.frameType = frameType;
    return this;
  }

   /**
   * The gear&#39;s frame type (bike only).
   * @return frameType
  **/
  @ApiModelProperty(value = "The gear's frame type (bike only).")
  public Integer getFrameType() {
    return frameType;
  }

  public void setFrameType(Integer frameType) {
    this.frameType = frameType;
  }

  public DetailedGear description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The gear&#39;s description.
   * @return description
  **/
  @ApiModelProperty(value = "The gear's description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedGear detailedGear = (DetailedGear) o;
    return Objects.equals(this.id, detailedGear.id) &&
        Objects.equals(this.resourceState, detailedGear.resourceState) &&
        Objects.equals(this.primary, detailedGear.primary) &&
        Objects.equals(this.name, detailedGear.name) &&
        Objects.equals(this.distance, detailedGear.distance) &&
        Objects.equals(this.brandName, detailedGear.brandName) &&
        Objects.equals(this.modelName, detailedGear.modelName) &&
        Objects.equals(this.frameType, detailedGear.frameType) &&
        Objects.equals(this.description, detailedGear.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceState, primary, name, distance, brandName, modelName, frameType, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedGear {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceState: ").append(toIndentedString(resourceState)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    frameType: ").append(toIndentedString(frameType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

