/*
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SummaryAthlete;
import io.swagger.client.model.SummaryClub;
import io.swagger.client.model.SummaryGear;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * DetailedAthlete
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T15:31:53.751+01:00")
public class DetailedAthlete {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("resource_state")
  private Integer resourceState = null;

  @SerializedName("firstname")
  private String firstname = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("profile_medium")
  private String profileMedium = null;

  @SerializedName("profile")
  private String profile = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("country")
  private String country = null;

  /**
   * The athlete&#39;s sex.
   */
  @JsonAdapter(SexEnum.Adapter.class)
  public enum SexEnum {
    M("M"),
    
    F("F");

    private String value;

    SexEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SexEnum fromValue(String text) {
      for (SexEnum b : SexEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SexEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SexEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SexEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SexEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("sex")
  private SexEnum sex = null;

  /**
   * Whether the currently logged-in athlete follows this athlete.
   */
  @JsonAdapter(FriendEnum.Adapter.class)
  public enum FriendEnum {
    PENDING("pending"),
    
    ACCEPTED("accepted"),
    
    BLOCKED("blocked");

    private String value;

    FriendEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FriendEnum fromValue(String text) {
      for (FriendEnum b : FriendEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FriendEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FriendEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FriendEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FriendEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("friend")
  private FriendEnum friend = null;

  /**
   * Whether this athlete follows the currently logged-in athlete.
   */
  @JsonAdapter(FollowerEnum.Adapter.class)
  public enum FollowerEnum {
    PENDING("pending"),
    
    ACCEPTED("accepted"),
    
    BLOCKED("blocked");

    private String value;

    FollowerEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FollowerEnum fromValue(String text) {
      for (FollowerEnum b : FollowerEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FollowerEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FollowerEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FollowerEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FollowerEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("follower")
  private FollowerEnum follower = null;

  @SerializedName("premium")
  private Boolean premium = null;

  @SerializedName("summit")
  private Boolean summit = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("follower_count")
  private Integer followerCount = null;

  @SerializedName("friend_count")
  private Integer friendCount = null;

  @SerializedName("mutual_friend_count")
  private Integer mutualFriendCount = null;

  /**
   * The athlete&#39;s preferred unit system.
   */
  @JsonAdapter(MeasurementPreferenceEnum.Adapter.class)
  public enum MeasurementPreferenceEnum {
    FEET("feet"),
    
    METERS("meters");

    private String value;

    MeasurementPreferenceEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MeasurementPreferenceEnum fromValue(String text) {
      for (MeasurementPreferenceEnum b : MeasurementPreferenceEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<MeasurementPreferenceEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MeasurementPreferenceEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MeasurementPreferenceEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return MeasurementPreferenceEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("measurement_preference")
  private MeasurementPreferenceEnum measurementPreference = null;

  @SerializedName("ftp")
  private Integer ftp = null;

  @SerializedName("weight")
  private Float weight = null;

  @SerializedName("clubs")
  private List<SummaryClub> clubs = null;

  @SerializedName("bikes")
  private List<SummaryGear> bikes = null;

  @SerializedName("shoes")
  private List<SummaryGear> shoes = null;

  public DetailedAthlete id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the athlete
   * @return id
  **/
  @ApiModelProperty(value = "The unique identifier of the athlete")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public DetailedAthlete resourceState(Integer resourceState) {
    this.resourceState = resourceState;
    return this;
  }

   /**
   * Resource state, indicates level of detail. Possible values: 1 -&gt; \&quot;meta\&quot;, 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
   * @return resourceState
  **/
  @ApiModelProperty(value = "Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"")
  public Integer getResourceState() {
    return resourceState;
  }

  public void setResourceState(Integer resourceState) {
    this.resourceState = resourceState;
  }

  public DetailedAthlete firstname(String firstname) {
    this.firstname = firstname;
    return this;
  }

   /**
   * The athlete&#39;s first name.
   * @return firstname
  **/
  @ApiModelProperty(value = "The athlete's first name.")
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public DetailedAthlete lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * The athlete&#39;s last name.
   * @return lastname
  **/
  @ApiModelProperty(value = "The athlete's last name.")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public DetailedAthlete profileMedium(String profileMedium) {
    this.profileMedium = profileMedium;
    return this;
  }

   /**
   * URL to a 62x62 pixel profile picture.
   * @return profileMedium
  **/
  @ApiModelProperty(value = "URL to a 62x62 pixel profile picture.")
  public String getProfileMedium() {
    return profileMedium;
  }

  public void setProfileMedium(String profileMedium) {
    this.profileMedium = profileMedium;
  }

  public DetailedAthlete profile(String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * URL to a 124x124 pixel profile picture.
   * @return profile
  **/
  @ApiModelProperty(value = "URL to a 124x124 pixel profile picture.")
  public String getProfile() {
    return profile;
  }

  public void setProfile(String profile) {
    this.profile = profile;
  }

  public DetailedAthlete city(String city) {
    this.city = city;
    return this;
  }

   /**
   * The athlete&#39;s city.
   * @return city
  **/
  @ApiModelProperty(value = "The athlete's city.")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public DetailedAthlete state(String state) {
    this.state = state;
    return this;
  }

   /**
   * The athlete&#39;s state or geographical region.
   * @return state
  **/
  @ApiModelProperty(value = "The athlete's state or geographical region.")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public DetailedAthlete country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The athlete&#39;s country.
   * @return country
  **/
  @ApiModelProperty(value = "The athlete's country.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public DetailedAthlete sex(SexEnum sex) {
    this.sex = sex;
    return this;
  }

   /**
   * The athlete&#39;s sex.
   * @return sex
  **/
  @ApiModelProperty(value = "The athlete's sex.")
  public SexEnum getSex() {
    return sex;
  }

  public void setSex(SexEnum sex) {
    this.sex = sex;
  }

  public DetailedAthlete friend(FriendEnum friend) {
    this.friend = friend;
    return this;
  }

   /**
   * Whether the currently logged-in athlete follows this athlete.
   * @return friend
  **/
  @ApiModelProperty(value = "Whether the currently logged-in athlete follows this athlete.")
  public FriendEnum getFriend() {
    return friend;
  }

  public void setFriend(FriendEnum friend) {
    this.friend = friend;
  }

  public DetailedAthlete follower(FollowerEnum follower) {
    this.follower = follower;
    return this;
  }

   /**
   * Whether this athlete follows the currently logged-in athlete.
   * @return follower
  **/
  @ApiModelProperty(value = "Whether this athlete follows the currently logged-in athlete.")
  public FollowerEnum getFollower() {
    return follower;
  }

  public void setFollower(FollowerEnum follower) {
    this.follower = follower;
  }

  public DetailedAthlete premium(Boolean premium) {
    this.premium = premium;
    return this;
  }

   /**
   * Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
   * @return premium
  **/
  @ApiModelProperty(value = "Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.")
  public Boolean isPremium() {
    return premium;
  }

  public void setPremium(Boolean premium) {
    this.premium = premium;
  }

  public DetailedAthlete summit(Boolean summit) {
    this.summit = summit;
    return this;
  }

   /**
   * Whether the athlete has any Summit subscription.
   * @return summit
  **/
  @ApiModelProperty(value = "Whether the athlete has any Summit subscription.")
  public Boolean isSummit() {
    return summit;
  }

  public void setSummit(Boolean summit) {
    this.summit = summit;
  }

  public DetailedAthlete createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time at which the athlete was created.
   * @return createdAt
  **/
  @ApiModelProperty(value = "The time at which the athlete was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public DetailedAthlete updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The time at which the athlete was last updated.
   * @return updatedAt
  **/
  @ApiModelProperty(value = "The time at which the athlete was last updated.")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public DetailedAthlete followerCount(Integer followerCount) {
    this.followerCount = followerCount;
    return this;
  }

   /**
   * The athlete&#39;s follower count.
   * @return followerCount
  **/
  @ApiModelProperty(value = "The athlete's follower count.")
  public Integer getFollowerCount() {
    return followerCount;
  }

  public void setFollowerCount(Integer followerCount) {
    this.followerCount = followerCount;
  }

  public DetailedAthlete friendCount(Integer friendCount) {
    this.friendCount = friendCount;
    return this;
  }

   /**
   * The athlete&#39;s friend count.
   * @return friendCount
  **/
  @ApiModelProperty(value = "The athlete's friend count.")
  public Integer getFriendCount() {
    return friendCount;
  }

  public void setFriendCount(Integer friendCount) {
    this.friendCount = friendCount;
  }

  public DetailedAthlete mutualFriendCount(Integer mutualFriendCount) {
    this.mutualFriendCount = mutualFriendCount;
    return this;
  }

   /**
   * The number or athletes mutually followed by this athlete and the currently logged-in athlete.
   * @return mutualFriendCount
  **/
  @ApiModelProperty(value = "The number or athletes mutually followed by this athlete and the currently logged-in athlete.")
  public Integer getMutualFriendCount() {
    return mutualFriendCount;
  }

  public void setMutualFriendCount(Integer mutualFriendCount) {
    this.mutualFriendCount = mutualFriendCount;
  }

  public DetailedAthlete measurementPreference(MeasurementPreferenceEnum measurementPreference) {
    this.measurementPreference = measurementPreference;
    return this;
  }

   /**
   * The athlete&#39;s preferred unit system.
   * @return measurementPreference
  **/
  @ApiModelProperty(value = "The athlete's preferred unit system.")
  public MeasurementPreferenceEnum getMeasurementPreference() {
    return measurementPreference;
  }

  public void setMeasurementPreference(MeasurementPreferenceEnum measurementPreference) {
    this.measurementPreference = measurementPreference;
  }

  public DetailedAthlete ftp(Integer ftp) {
    this.ftp = ftp;
    return this;
  }

   /**
   * The athlete&#39;s FTP (Functional Threshold Power).
   * @return ftp
  **/
  @ApiModelProperty(value = "The athlete's FTP (Functional Threshold Power).")
  public Integer getFtp() {
    return ftp;
  }

  public void setFtp(Integer ftp) {
    this.ftp = ftp;
  }

  public DetailedAthlete weight(Float weight) {
    this.weight = weight;
    return this;
  }

   /**
   * The athlete&#39;s weight.
   * @return weight
  **/
  @ApiModelProperty(value = "The athlete's weight.")
  public Float getWeight() {
    return weight;
  }

  public void setWeight(Float weight) {
    this.weight = weight;
  }

  public DetailedAthlete clubs(List<SummaryClub> clubs) {
    this.clubs = clubs;
    return this;
  }

  public DetailedAthlete addClubsItem(SummaryClub clubsItem) {
    if (this.clubs == null) {
      this.clubs = new ArrayList<SummaryClub>();
    }
    this.clubs.add(clubsItem);
    return this;
  }

   /**
   * The athlete&#39;s clubs.
   * @return clubs
  **/
  @ApiModelProperty(value = "The athlete's clubs.")
  public List<SummaryClub> getClubs() {
    return clubs;
  }

  public void setClubs(List<SummaryClub> clubs) {
    this.clubs = clubs;
  }

  public DetailedAthlete bikes(List<SummaryGear> bikes) {
    this.bikes = bikes;
    return this;
  }

  public DetailedAthlete addBikesItem(SummaryGear bikesItem) {
    if (this.bikes == null) {
      this.bikes = new ArrayList<SummaryGear>();
    }
    this.bikes.add(bikesItem);
    return this;
  }

   /**
   * The athlete&#39;s bikes.
   * @return bikes
  **/
  @ApiModelProperty(value = "The athlete's bikes.")
  public List<SummaryGear> getBikes() {
    return bikes;
  }

  public void setBikes(List<SummaryGear> bikes) {
    this.bikes = bikes;
  }

  public DetailedAthlete shoes(List<SummaryGear> shoes) {
    this.shoes = shoes;
    return this;
  }

  public DetailedAthlete addShoesItem(SummaryGear shoesItem) {
    if (this.shoes == null) {
      this.shoes = new ArrayList<SummaryGear>();
    }
    this.shoes.add(shoesItem);
    return this;
  }

   /**
   * The athlete&#39;s shoes.
   * @return shoes
  **/
  @ApiModelProperty(value = "The athlete's shoes.")
  public List<SummaryGear> getShoes() {
    return shoes;
  }

  public void setShoes(List<SummaryGear> shoes) {
    this.shoes = shoes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedAthlete detailedAthlete = (DetailedAthlete) o;
    return Objects.equals(this.id, detailedAthlete.id) &&
        Objects.equals(this.resourceState, detailedAthlete.resourceState) &&
        Objects.equals(this.firstname, detailedAthlete.firstname) &&
        Objects.equals(this.lastname, detailedAthlete.lastname) &&
        Objects.equals(this.profileMedium, detailedAthlete.profileMedium) &&
        Objects.equals(this.profile, detailedAthlete.profile) &&
        Objects.equals(this.city, detailedAthlete.city) &&
        Objects.equals(this.state, detailedAthlete.state) &&
        Objects.equals(this.country, detailedAthlete.country) &&
        Objects.equals(this.sex, detailedAthlete.sex) &&
        Objects.equals(this.friend, detailedAthlete.friend) &&
        Objects.equals(this.follower, detailedAthlete.follower) &&
        Objects.equals(this.premium, detailedAthlete.premium) &&
        Objects.equals(this.summit, detailedAthlete.summit) &&
        Objects.equals(this.createdAt, detailedAthlete.createdAt) &&
        Objects.equals(this.updatedAt, detailedAthlete.updatedAt) &&
        Objects.equals(this.followerCount, detailedAthlete.followerCount) &&
        Objects.equals(this.friendCount, detailedAthlete.friendCount) &&
        Objects.equals(this.mutualFriendCount, detailedAthlete.mutualFriendCount) &&
        Objects.equals(this.measurementPreference, detailedAthlete.measurementPreference) &&
        Objects.equals(this.ftp, detailedAthlete.ftp) &&
        Objects.equals(this.weight, detailedAthlete.weight) &&
        Objects.equals(this.clubs, detailedAthlete.clubs) &&
        Objects.equals(this.bikes, detailedAthlete.bikes) &&
        Objects.equals(this.shoes, detailedAthlete.shoes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceState, firstname, lastname, profileMedium, profile, city, state, country, sex, friend, follower, premium, summit, createdAt, updatedAt, followerCount, friendCount, mutualFriendCount, measurementPreference, ftp, weight, clubs, bikes, shoes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedAthlete {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceState: ").append(toIndentedString(resourceState)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    profileMedium: ").append(toIndentedString(profileMedium)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    friend: ").append(toIndentedString(friend)).append("\n");
    sb.append("    follower: ").append(toIndentedString(follower)).append("\n");
    sb.append("    premium: ").append(toIndentedString(premium)).append("\n");
    sb.append("    summit: ").append(toIndentedString(summit)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    followerCount: ").append(toIndentedString(followerCount)).append("\n");
    sb.append("    friendCount: ").append(toIndentedString(friendCount)).append("\n");
    sb.append("    mutualFriendCount: ").append(toIndentedString(mutualFriendCount)).append("\n");
    sb.append("    measurementPreference: ").append(toIndentedString(measurementPreference)).append("\n");
    sb.append("    ftp: ").append(toIndentedString(ftp)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    clubs: ").append(toIndentedString(clubs)).append("\n");
    sb.append("    bikes: ").append(toIndentedString(bikes)).append("\n");
    sb.append("    shoes: ").append(toIndentedString(shoes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

