/*
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Error
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T15:31:53.751+01:00")
public class Error {
  @SerializedName("code")
  private String code = null;

  @SerializedName("field")
  private String field = null;

  @SerializedName("resource")
  private String resource = null;

  public Error code(String code) {
    this.code = code;
    return this;
  }

   /**
   * The code associated with this error.
   * @return code
  **/
  @ApiModelProperty(value = "The code associated with this error.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Error field(String field) {
    this.field = field;
    return this;
  }

   /**
   * The specific field or aspect of the resource associated with this error.
   * @return field
  **/
  @ApiModelProperty(value = "The specific field or aspect of the resource associated with this error.")
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public Error resource(String resource) {
    this.resource = resource;
    return this;
  }

   /**
   * The type of resource associated with this error.
   * @return resource
  **/
  @ApiModelProperty(value = "The type of resource associated with this error.")
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.code, error.code) &&
        Objects.equals(this.field, error.field) &&
        Objects.equals(this.resource, error.resource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, field, resource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

